Перевел все на конфигурирование аннотациями. Не понятно почему не работает локализация.
deft1991/otusHomeWork pull request #1
Opened 2018-07-01 13:58 UTC by deft1991

2018-07-04 06:28 UTC, ydvorzhetskiy approved these changes

2018-07-04 06:28 UTC, ydvorzhetskiy commented on .gitignore
> +.idea
`.idea/` - иначе он подумает,что это файл.
*.iml
target/

2018-07-04 06:28 UTC, ydvorzhetskiy commented on build.gradle
> +    junit = "4.12"
junitVersion, lombokVersion )))))

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/Application.java
> +        AnswerAnalyzer answerAnalyzer = context.getBean(AnswerService.class);
Неа, из контекста мы достаём по интерфейсу. А вот какая реализация в итоге будет - это дело конфигурации контекста. По конкретному классу доставать - это нарушение зависимости от абстракций

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/Application.java
> +        messageSource.setBasename("/src/main/resources/bundle");
Неа. classpath:/bundle или просто /bundle

src/main/resources после сборки у Вас пропадут.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/resources/bundle.properties
> +helloName= ������! ��� ���� �����?
Ха, а почему два русских бандла?)

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/resources/application.properties
> +person.defaultFirstName=DefaultFirsName
Да и не нужно это.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/resources/application.properties
> +file.csvFile=src/main/resources/questions.csv
Вот тут опять /questions.csv

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/QuestionReaderService.java
> +    private final BufferedReader bufferedReader;
Повторюсь, Buffered redaer - это совсем сомнительный параметр.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/QuestionReaderService.java
> +        } catch (IOException e) {
И вот этого тогда бы не было

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/configuration/BaseConfig.java
> +    BufferedReader bufferedReader(FileReader fileReader) {
Круто, что вы вынесли абстракцию, но мне, кажется лучше выносить без ридеров - а анпример прочитать из консоли строчку или записать строчку в консоль.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/configuration/BaseConfig.java
> +    BufferedReader bufferedReader(FileReader fileReader) {
Да, и где интерфейс? У них обоих есть прекрасный интерфейс Reader

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/domain/Person.java
> +    private String firstName;
final

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/configuration/BaseConfig.java
> +    String csvFile;
private

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +        if ("Q".equalsIgnoreCase(arrValues[0])) {
Мгическая константа, просьба её вынести и дать осмысленное имя.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +        System.out.println(messageSource.getMessage("helloName", new String[0], Locale.forLanguageTag("ru")));
ru-RU правильный language tag. Есть целый стандарт ISO для названий локалей. В исходниках Locale омжно найти на него ссылку.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/resources/bundle.properties
> +lastName= � ����� ���� �������?
И обынчо они пишутся через точнку. И не скупитесь на расширенные называния:
csv.read.error=Ой...
your.result.is=
Пробелами они не отделяются от знака равно. Всё что после пробела - уже сообщение.

2018-07-04 06:28 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +                if (answer.equalsIgnoreCase(arrValues[2].split("-")[0].trim())
тоже немного магии с -

2018-07-04 06:31 UTC, ydvorzhetskiy requested changes
Случайно заппрувил - а хотел вернуть на доработку)

2018-07-06 07:01 UTC, deft1991 commented on .gitignore
> +.idea
+

2018-07-06 07:01 UTC, deft1991 commented on build.gradle
> +    junit = "4.12"
+

2018-07-06 07:02 UTC, deft1991 commented on src/main/java/otus/homework/deft/Application.java
> +        AnswerAnalyzer answerAnalyzer = context.getBean(AnswerService.class);
+

2018-07-06 07:02 UTC, deft1991 commented on src/main/java/otus/homework/deft/Application.java
> +        messageSource.setBasename("/src/main/resources/bundle");
+

2018-07-06 07:02 UTC, deft1991 commented on src/main/resources/bundle.properties
> +helloName= ������! ��� ���� �����?
+

2018-07-06 07:02 UTC, deft1991 commented on src/main/resources/application.properties
> +person.defaultFirstName=DefaultFirsName
Ну это я оставляю что б для практики =)

2018-07-06 07:08 UTC, deft1991 commented on src/main/java/otus/homework/deft/service/QuestionReaderService.java
> +    private final BufferedReader bufferedReader;
+

2018-07-06 07:10 UTC, deft1991 commented on src/main/java/otus/homework/deft/domain/Person.java
> +    private String firstName;
+

2018-07-06 07:10 UTC, deft1991 commented on src/main/java/otus/homework/deft/configuration/BaseConfig.java
> +    String csvFile;
+

2018-07-06 07:13 UTC, deft1991 commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +        if ("Q".equalsIgnoreCase(arrValues[0])) {
+

2018-07-06 07:14 UTC, deft1991 commented on src/main/java/otus/homework/deft/domain/Person.java
> +    private String firstName;
не. это ж не файнал. это поля класса

2018-07-06 07:14 UTC, deft1991 commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +        System.out.println(messageSource.getMessage("helloName", new String[0], Locale.forLanguageTag("ru")));
Огромное спасибо +

2018-07-06 07:20 UTC, deft1991 commented on src/main/resources/application.properties
> +file.csvFile=src/main/resources/questions.csv
не удается убрать

2018-07-08 10:36 UTC, ydvorzhetskiy approved these changes

2018-07-08 10:36 UTC, ydvorzhetskiy commented on .idea/misc.xml
> +  <component name="JavaScriptSettings">
Хех, но это файл из гита тоже нужно удалить) `git rm .idea/`

2018-07-08 10:36 UTC, ydvorzhetskiy commented on build.gradle
> +    lombokVersion = "1.18.0"
Красотища!))))

2018-07-08 10:36 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/AnswerService.java
> +                if (answer.equalsIgnoreCase(arrValues[2].split(REGEX_SPLITTER)[0].trim())
ВОт!! Красота же)

2018-07-08 10:36 UTC, ydvorzhetskiy commented on src/main/java/otus/homework/deft/service/QuestionReaderService.java
> +    private String csvFile;
Вот всё равно лучше через параметр конструктора это передать.

2018-07-08 10:36 UTC, ydvorzhetskiy commented on src/main/resources/application.properties
> +file.csvFile=src/main/resources/questions.csv
Ну и ладно)) Всё равно рекомендую прочитать про ClassLoader.getReaourceAsStream()

2018-07-12 07:00 UTC, merged